### ISSUE TITLE
no such module 'FirebaseCore' in CapacitorFirebaseAnalytics

### ISSUE THREAD

**Issue by YanouonaY** [basvdijk/capacitor4-firebase-analytics-example-project-capawesome-team#3]
Hello,

It's not an issue but a question.

I have a capacitor project with plugins:
- "@capacitor-firebase/analytics": "^5.4.0",
- "@capacitor-firebase/crashlytics": "^5.4.0",
- "firebase": "^10.7.2"

For Android, all is ok

For, iOS, I added the specific line in pod file, I added google-service-info.plist but when I run with Xcode I've got an error in CapacitorFirebaseAnalytics --> "no such module 'FirebaseCore'"

Can I help me?

Thanks

**Comment by basvdijk** [comment]
Looks like the Pod in not stalled. Did you see the same output as shown on https://github.com/basvdijk/capacitor4-firebase-analytics-example-project-capawesome-team?tab=readme-ov-file#installing-pods when running `pod install`?

**Comment by YanouonaY** [comment]
yes

**Comment by YanouonaY** [comment]
Besides, I tried with firebase from capacitor-community, all it was ok. It didn't run with firebase from capawesome-team. What is the difference?

**Comment by basvdijk** [comment]
I honestly don't know. I know it is sometimes a pain to get this Capacitor stuff working. Glad you fixed it! :)

**Comment by YanouonaY** [comment]
excuse me, i forgot the specific pod in target 

pod 'CapacitorFirebaseAnalytics/Analytics', :path => '../../node_modules/@capacitor-firebase/analytics'

**Comment by basvdijk** [comment]
So my instructions were valid but you forgot to add this?
